### ISSUE TITLE
RIDE (Robot IDE) fails to import properly PuppeteerLibrary

### ISSUE THREAD

**Issue by godchaser** [qahive/robotframework-puppeteer#103]
When trying to run demo project, on load of PuppeteerLibrary library RIDE (https://github.com/robotframework/RIDE) throws this error (click Tools-View RIDE Log). That's why keyword auto-completion does not work anymore, even though tests can be run. I used many libraries with RIDE, and had no problems. So I think this might be robotframework-puppeteer error, even though RIDE might have a bug also.

20210331 07:49:36.900 [INFO]: **Found Robot Framework version 4.0** from d:\py3venv\lib\site-packages\robot.

20210331 07:49:36.900 [INFO]: Started **RIDE v2.0b1 using python version 3.8.5 with wx version 4.0.7.post2 in win32**.

20210331 07:49:38.053 [WARN]: **Importing test library "PuppeteerLibrary" failed**

Traceback (most recent call last):
Initializing test library 'PuppeteerLibrary' with no arguments failed: ValueError: signal only works in main thread
Traceback (most recent call last):
  File "d:\py3venv\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 167, in _get_instance
    return libcode(*self.positional_args, **dict(self.named_args))
  File "d:\py3venv\lib\site-packages\PuppeteerLibrary\__init__.py", line 119, in __init__
    signal.signal(signal.SIGINT, self.terminal_signal_handler)
  File "C:\Python38\lib\signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
  File "d:\py3venv\lib\site-packages\robotide\spec\librarymanager.py", line 82, in _fetch_keywords
    return get_import_result(path, library_args)
  File "d:\py3venv\lib\site-packages\robotide\spec\libraryfetcher.py", line 21, in get_import_result
    lib = robotapi.TestLibrary(path, args)
  File "d:\py3venv\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 54, in TestLibrary
    lib.create_handlers()
  File "d:\py3venv\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 100, in create_handlers
    self._create_handlers(self.get_instance())
  File "d:\py3venv\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 159, in get_instance
    self._libinst = self._get_instance(self._libcode)
  File "d:\py3venv\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 169, in _get_instance
    self._raise_creating_instance_failed()
  File "d:\py3venv\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 313, in _raise_creating_instance_failed
    raise DataError("Initializing test library '%s' with %s failed: %s\n%s"

**Comment by atthaboon** [comment]
Plz install from master branch first this issue will be released with v3.0.3
