### ISSUE TITLE
i can run in roborframework butit import fail and can not find PuppeteerLibrary under ride.

### ISSUE THREAD

**Issue by nixuewei** [qahive/robotframework-puppeteer#24]
it so strange, i can run in roborframework butit import fail and can not find PuppeteerLibrary under ride.
i use mac os catalina 10.15.5.  python 3.7.7 robotframework==3.2.1 robotframework-ride=v2.0b1

20200729 09:35:52.251 [WARN]: Importing test library "PuppeteerLibrary" failed

Traceback (most recent call last):
Importing test library 'PuppeteerLibrary' failed: There is no current event loop in thread 'Thread-1'.
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/robotide/lib/robot/utils/importer.py", line 153, in _import
    return __import__(name, fromlist=fromlist)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PuppeteerLibrary/__init__.py", line 8, in <module>
    from PuppeteerLibrary.keywords import (
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PuppeteerLibrary/keywords/__init__.py", line 1, in <module>
    from .alert import AlertKeywords
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PuppeteerLibrary/keywords/alert.py", line 1, in <module>
    from PuppeteerLibrary.base.librarycomponent import LibraryComponent
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PuppeteerLibrary/base/librarycomponent.py", line 3, in <module>
    from PuppeteerLibrary.base.context import ContextAware
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PuppeteerLibrary/base/context.py", line 3, in <module>
    class ContextAware(object):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PuppeteerLibrary/base/context.py", line 5, in ContextAware
    loop = asyncio.get_event_loop()
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/events.py", line 644, in get_event_loop
    % threading.current_thread().name)
PYTHONPATH:
  /usr/local/bin
  /usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python37.zip
  /usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7
  /usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload
  /Users/ming.ni/Library/Python/3.7/lib/python/site-packages
  /usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
  /usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/robotide/spec
  /usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/robotide/lib
  /usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/robotide/contrib/testrunner/../../lib
  /usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/robotide/contrib/testrunner/../../lib
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/robotide/spec/librarymanager.py", line 82, in _fetch_keywords
    return get_import_result(path, library_args)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/robotide/spec/libraryfetcher.py", line 21, in get_import_result
    lib = robotapi.TestLibrary(path, args)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/robotide/lib/robot/running/testlibraries.py", line 50, in TestLibrary
    return_source=True)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/robotide/lib/robot/utils/importer.py", line 72, in import_class_or_module
    self._raise_import_failed(name, err)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/robotide/lib/robot/utils/importer.py", line 109, in _raise_import_failed
    raise DataError('\n'.join(msg))

**Comment by atthaboon** [comment]
1. Could you share a Puppeteer library version here? run command **pip freeze**
2. Could you share your script here?

**Comment by nixuewei** [comment]
Puppeteer library：
robotframework-PuppeteerLibrary==1.0.0，

Script：
`*** Settings ***
Test Teardown     Close Browser
Library           PuppeteerLibrary

*** Test Cases ***
Example login form submit
    ${HEADLESS}    Get variable value    ${HEADLESS}    ${False}
    &{options} =    create dictionary    headless=${HEADLESS}
    Open browser    https://www.baidu.com    options=${options}
    Maximize Browser Window
    Input text    id:kw    demo
    Click Element    id:su`

if run use command or run in robotframework, it works.  but ride give import library failed and can't check library by F5 and display red on robotframework

**Comment by atthaboon** [comment]
Confirmed also happen on my Window RIDE.
I need to recheck first why RIDE can't access the library. 

You can also try eclipse + RED plugin. It's working fine.

**Comment by atthaboon** [comment]
Issue resolved: 
Please try update robotframework puppeteer to version 1.0.1
https://github.com/qahive/robotframework-puppeteer/pull/25

**Comment by nixuewei** [comment]
Hi atthaboon, 
Thank your for your rapid response.  It has been work well on my Macos after upgrade 1.0.1.  Great Thanks!
